// <auto-generated />
namespace Cinema.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SQL_Movie_Users_FK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SQL_Movie_Users_FK));
        
        string IMigrationMetadata.Id
        {
            get { return "201705261141382_SQL_Movie_Users_FK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
